version: "3.9"
services:
  csvserver:
    image: "infracloudio/csvserver:latest"
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata/
    environment:
    - CSVSERVER_BORDER=Orange
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
